config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'
  resources :users, only: [:show, :create, :edit, :update, :delete, :destroy]
  get '/reviews/new' => 'reviews#dummy_new', as: 'dummy_review'
  resources :reviews, except: [:index, :new]
  resources :upvotes, only: [:create, :destroy]
  resources :restaurants, only: [:show, :create]
  resources :searches, only: [:create, :update]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  post '/new_restaurant' => 'restaurants#dummy_create'
  get '/search/:query' => 'searches#show', as: 'search_result'
# conflict start
  get '/restaurants/:restaurant_id/reviews/new' => 'reviews#new', as: 'new_review'
  post '/restaurants/:restaurant_id/reviews' => 'reviews#create', as: 'post_review'
  # analytics page
  get '/analytics' => 'application#analytics', as: 'analytics'
  post '/preview' => 'reviews#homepage_poster', as: 'post_from_homepage'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  has_many :reviews
  has_many :users, through: :reviews

  validates :foursquare_id, uniqueness: true
  validates :name, :address, presence: true

  def set_attributes
    if last_updated.nil? || Time.now - last_updated > 90000
      response = api_call
      set_contact_info(response) if response["url"]
      set_photos(response)
      self.name = response["name"]
      self.address = response["location"]["formattedAddress"].join("~")
      self.url = response["url"] if response["url"]
      self.menu = response["menu"]["url"] if response ["menu"]
      self.price_tier = response["price"]["tier"] if response["price"]
      self.last_updated = Time.now
    end
  end

  def api_call
    query_url = "https://api.foursquare.com/v2/venues/#{foursquare_id}?v=#{Time.now.strftime("%Y%m%d")}&client_id=#{ENV['foursquare_client_id']}&client_secret=#{ENV['foursquare_client_secret']}"
    JSON.parse(RestClient.get(query_url))["response"]["venue"]
  end

  def set_contact_info(response)
    self.phone = response["contact"]["formattedPhone"]
    self.twitter = response["contact"]["twitter"]
    self.facebook = response["contact"]["facebook"]
  end

  def set_photos(response)
    if !response["photos"]["groups"].empty?
      photos = response["photos"]["groups"][0]["items"]
      photo = photos.max_by {|attrs| attrs["width"]}
      self.photo = "#{photo["prefix"]}#{photo["width"]}x#{photo["height"]}#{photo["suffix"]}"
    else
      self.photo = "/default_header.jpg"
    end
  end

  def first_x_reviews(x)
    Review.where(restaurant_id: self.id).order("updated_at DESC").limit(10)
  end

  # testing purposes
  def spaced_address
    address.split('~').join(' ')
  end

  # analytics
  def restaurant_avg_rating
    sum = 0
    self.reviews.each do |review|
      sum += review.avg_rating
    end
      (sum / self.reviews.count.to_f).round(2).to_s
  end

  def self.top_5_rated_restaurants
    hash = {}
    Restaurant.all.each do |restaurant|
      hash[restaurant.name] = restaurant.restaurant_avg_rating
    end
    hash.sort_by {|key, value| value }.reverse[0..4]
  end

  def self.lowest_5_rated_restaurants
    hash = {}
    Restaurant.all.each do |restaurant|
      hash[restaurant.name] = restaurant.restaurant_avg_rating
    end
    hash.sort_by {|key, value| value }[0..4]
  end

  def avg_food_rating
    sum = 0
    self.reviews.each do |review|
      sum += review.food_rating
    end
      (sum / self.reviews.count.to_f).round(2).to_s
  end

  def self.top_5_food_rated
    hash = {}
    Restaurant.all.each do |restaurant|
      hash[restaurant.name] = restaurant.avg_food_rating
    end # returns a hash here
    hash.sort_by {|key, value| value }.reverse[0..4]
  end

  def avg_environment_rating
    sum = 0
    self.reviews.each do |review|
      sum += review.environment_rating
    end
      (sum / self.reviews.count.to_f).round(2).to_s
  end

  def self.top_5_environment_rated
    hash = {}
    Restaurant.all.each do |restaurant|
      hash[restaurant.name] = restaurant.avg_environment_rating
    end
    hash.sort_by {|key, value| value }.reverse[0..4]
  end

  def avg_service_rating
    sum = 0
    self.reviews.each do |review|
      sum += review.service_rating
    end
      (sum / self.reviews.count.to_f).round(2).to_s
  end

  def self.top_5_service_rated
    hash = {}
    Restaurant.all.each do |restaurant|
      hash[restaurant.name] = restaurant.avg_service_rating
    end
    hash.sort_by {|key, value| value }.reverse[0..4]
  end

  def self.most_reviewed_restaurant
    hash = {}
    Restaurant.all.each do |restaurant|
      hash[restaurant.name] = restaurant.reviews.count
    end
    hash.sort_by {|key, value| value }.reverse[0..4]
  end

  def self.food_delta_helper
    hash = {}
    Restaurant.all.each do |restaurant|
      hash[restaurant.name] = restaurant.avg_food_rating
    end
    hash
  end

  def self.service_delta_helper
    hash = {}
    Restaurant.all.each do |restaurant|
      hash[restaurant.name] = restaurant.avg_service_rating
    end
    hash
  end

  def self.highest_food_lowest_service
    hash1 = (Restaurant.food_delta_helper) # restaurant.name, food_rating
    hash2 = Restaurant.service_delta_helper # restaurant.name, service_rating
    hash3 = {}
    hash1.keys.each do |res_name|
      hash3[res_name] = hash1[res_name].to_f - hash2[res_name].to_f
    end
    hash3.sort_by {|key, value| value }.reverse[0..4]
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def dummy_create
    find_user
    session[:dummy_restaurant] = Restaurant.new(name: params[:name], address: params[:address].join("~"), foursquare_id: params[:foursquare_id])
    session[:reformatted_address] = session[:dummy_restaurant].address.split("~")
    session[:dummy_restaurant].set_attributes
    render :'/restaurants/dummy_show'
  end

  def show
    find_user
    @restaurant = Restaurant.find(params[:id])
    @restaurant.set_attributes
    @restaurant.save
    @user_review = @user.owns_restaurant_review(@restaurant)[0] if @user
    if @user_review
      @reviews = @restaurant.first_x_reviews(9)
    else
      @reviews = @restaurant.first_x_reviews(10)
    end
  end

  def all_reviews
    render :'/restaurants/all_reviews'
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :foursquare_id)
  end

end

app/views/restaurants/dummy_show.html.erb
<style>
  .header {
    background: linear-gradient(45deg,
      rgba(0, 0, 0, 0.45),
      rgba(0, 0, 0, 0.45)
    ), url("<%= session[:dummy_restaurant].photo %>") center;
    background-size: cover;
  }
</style>


<div class="header">
  <h1><%= session[:dummy_restaurant].name %></h1>
</div>

<div class="socials">
  <% socials = {phone: session[:dummy_restaurant].phone, facebook: session[:dummy_restaurant].facebook, twitter: session[:dummy_restaurant].twitter, globe: session[:dummy_restaurant].url}.compact %>
  <% socials.each do |k, v| %>
  <a href="
    <% case k %>
    <% when :phone %>
    <%= "tel:#{v.tr('^0-9','')}" %>
    <% when :facebook %>
    <%= "https://facebook.com/#{v}" %>
    <% when :twitter %>
    <%= "https://twitter.com/#{v}" %>
    <% when :globe %>
    <%= v %>
    <% end %>
  ">
    <i class="fa fa-<%= k.to_s %> fa-lg"></i>
  </a>
  <% end %>
</div>

<h4 id="review_list_header">Reviews list</h4>
<p>None here yet — be the first!</p>
<%= link_to 'Create a new review for this restaurant', dummy_review_path %>

app/views/restaurants/show.html.erb
<style>
  .header {
    background: linear-gradient(45deg,
      rgba(0, 0, 0, 0.45),
      rgba(0, 0, 0, 0.45)
    ), url("<%= @restaurant.photo %>") center;
    background-size: cover;
  }
</style>


<div class="header">
  <h1><%= @restaurant.name %></h1>
</div>

<div class="socials">
  <% socials = {phone: @restaurant.phone, facebook: @restaurant.facebook, twitter: @restaurant.twitter, globe: @restaurant.url}.compact %>
  <% socials.each do |k, v| %>
  <a href="
    <% case k %>
    <% when :phone %>
    <%= "tel:#{v.tr('^0-9','')}" %>
    <% when :facebook %>
    <%= "https://facebook.com/#{v}" %>
    <% when :twitter %>
    <%= "https://twitter.com/#{v}" %>
    <% when :globe %>
    <%= v %>
    <% end %>
  ">
    <i class="fa fa-<%= k.to_s %> fa-lg"></i>
  </a>
  <% end %>
</div>

<% if flash[:notice] %>
<div class="notice">
  <%= flash[:notice] %>
</div>
<% end %>

<div class="reviews_wrapper">
  <% if @reviews.count == 0 %>
  <p class="notice">No reviews posted for this place yet... be the first!</p>
  <% end %>

<% if @user && !@user_review %>
<div class="post-review-button">
  <%= button_to 'Post a Review', new_review_path(@restaurant.id), method: :get, class: "nav_elements", id: "new_review_button" %>
</div>
<% end %>

<% unless @reviews.empty? %>

  <% if @user && @user_review %>
      <div class="centerer"><h4>Here's your review, <%= link_to @user.name, @user %></h4>

    <div class="review">
      <div class="review-title">
        <%= link_to @user_review.title, @user_review %>
      </div>
    </div>
  </div>
      <section class="review-content">
          <section class="review-title">
            <%= @user_review.title %>
          </section>
          <section class="ratings">
            <% @user_review.ratings_hash.each do |k, v| %>
              <div class='<%= k.downcase %>-rating'>
              <% v.times do |n| %>
                <i class="fa fa-star"></i>
              <% end %>
              <% (5-v).times do |n| %>
                <i class="fa fa-star-o"></i>
              <% end %>
              <%= k %>
            </div>
            <% end %>
          </section>
        <section class="review-text">
            <%= simple_format(@user_review.content.truncate_words(100)) %>
        </section>
        </section>
        <%= button_to 'Edit your review', edit_review_path(@user_review.id), method: 'get', class: 'submittable nav_elements' %>
      </div>
      <br>
  <% end %>

  <% @reviews.each do |review| %>
  <% unless review.user.id == @user.id %>
    <div class="review">
      <div class="user-info">
        <strong><%= link_to review.user.name, user_path(review.user) %>'s review:</strong>
      </div>
      <section class="review-content">
          <section class="review-title ">
            <%= review.title %>
          </section>
          <section class="ratings">
            <% review.ratings_hash.each do |k, v| %>
              <div class='<%= k.downcase %>-rating'>
              <% v.times do |n| %>
                <i class="fa fa-star"></i>
              <% end %>
              <%= k %>
            </div>
            <% end %>
          </section>
          <section class="review-text">
            <%= simple_format(review.content.truncate_words(100)) %>
        </section>
        </section>
      </div>
    <% end %>
    <br>
  <% end %>
<% end %>
</div>