config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'
  resources :users, only: [:show, :create, :edit, :update, :delete, :destroy]
  get '/reviews/new' => 'reviews#dummy_new', as: 'dummy_review'
  resources :reviews, except: [:index, :new]
  resources :upvotes, only: [:create, :destroy]
  resources :restaurants, only: [:show, :create]
  resources :searches, only: [:create, :update]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  post '/new_restaurant' => 'restaurants#dummy_create'
  get '/search/:query' => 'searches#show', as: 'search_result'
# conflict start
  get '/restaurants/:restaurant_id/reviews/new' => 'reviews#new', as: 'new_review'
  post '/restaurants/:restaurant_id/reviews' => 'reviews#create', as: 'post_review'
  # analytics page
  get '/analytics' => 'application#analytics', as: 'analytics'
  post '/preview' => 'reviews#homepage_poster', as: 'post_from_homepage'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?

  def index
    find_user
    @review = Review.new
    @search = Search.new
  end

  def analytics
    find_user
  end



  private

  def authenticate_user
    redirect_to root_path if !logged_in?
  end

  def logged_in?
    !!session[:user_id]
  end

  private

  def find_user
    @user = User.find(session[:user_id]) if session[:user_id]
    @user ||= User.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/analytics.html.erb
<h1>Trending: Restaurants</h1>

<div class="analytics">
<h2>Top 5 overall rated restaurants:</h2>
<%= column_chart Restaurant.top_5_rated_restaurants, max: 5, colors: ["rgba(255,83,77,1)"] %></br>
</div>

<div class="analytics">
<h2>Top 5 restaurants with the highest food rating:</h2>
<%= column_chart Restaurant.top_5_food_rated, max: 5, colors: ["rgba(255,83,77,1)"] %></br>
</div>

<div class="analytics">
<h2>Top 5 restaurants with the highest environment rating:</h2>
<%= column_chart Restaurant.top_5_environment_rated, max: 5, colors: ["rgba(255,83,77,1)"] %></br>
</div>

<div class="analytics">
<h2>Top 5 restaurants with the highest service rating:</h2>
<%= column_chart Restaurant.top_5_service_rated, max: 5, colors: ["rgba(255,83,77,1)"] %></br>
</div>

<div class="analytics">
<h2>Top 5 most reviewed restaurants:</h2>
<%= column_chart Restaurant.most_reviewed_restaurant, colors: ["rgba(255,83,77,1)"] %>
</div>

<div class="analytics">
<h2>Top 5 restaurants with the highest food rating / lowest service rating:</h2>
<%= column_chart Restaurant.highest_food_lowest_service, max: 5, colors: ["rgba(255,83,77,1)"] %>
</div>

<div class="analytics">
<h2>Top 5 restaurants with the lowest overall rating:</h2>
<%= column_chart Restaurant.lowest_5_rated_restaurants, max: 5, colors: ["rgba(255,83,77,1)"] %></br>
</div>


<h1>Trending: Users</h1>


<div class="analytics">
<h2>Top 5 users who have written the most reviews:</h2>
<%= column_chart User.top_reviewers, max: 5, colors: ["rgba(255,83,77,1)"] %>
</div>


<h1>Trending: Location</h1>


<div class="analytics">
<h2>Top 5 most popular location searches:</h2>
<p>
  <table>
    <tr>
      <th>Zipcode</th>
      <th>Count</th>
    </tr>
    <% Review.most_searched_zipcode.each do |obj| %>
      <tr>
        <td><%= obj.location %></td>
        <td><%= obj.count %></td>
      </tr>
    <% end %>
  </table>
</div>


</p>

app/views/application/index.html.erb
<% if flash[:message] %>
<div class="outer-container">
  <p class="notice">
    <%= flash[:message] %>
  </p>
</div>
<% end %>


<% if session[:user_id] %>
  <%= form_for @review, url: post_from_homepage_path do |f| %>
    <div class="full_width_wrapper">
      <%= f.text_field :title, placeholder: 'Title', autocomplete: "off"; %>
    </div>

    <div class="full_width_wrapper">
      <%= f.text_area :content, placeholder: 'Start blogging about your most recent restaurant experience here.' %>
    </div>
    <div class="query_box_wrapper">
      <%= f.text_field :search, placeholder: "Restaurant name?", class: "query_box" %>
    <%= f.text_field :location, placeholder: 'And where was it?', class: "query_box" %>
    <%= f.hidden_field :user_id, value: @user.id %>
  </div>
  <div class="full_width_wrapper"></div>
    <div id="submit_post">
      <%= f.submit 'Preview post', class: 'submittable nav_elements', id: 'post_button' %>
    </div>
  <% end %>
<% else %>
<div id="splash_wrapper">
  <h1 id="cta">Make your restaurant reviews beautiful. <%= link_to "Click here", login_path %> to get started.</h1>
</div>
<% end %>