config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'
  resources :users, only: [:show, :create, :edit, :update, :delete, :destroy]
  get '/reviews/new' => 'reviews#dummy_new', as: 'dummy_review'
  resources :reviews, except: [:index, :new]
  resources :upvotes, only: [:create, :destroy]
  resources :restaurants, only: [:show, :create]
  resources :searches, only: [:create, :update]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  post '/new_restaurant' => 'restaurants#dummy_create'
  get '/search/:query' => 'searches#show', as: 'search_result'
# conflict start
  get '/restaurants/:restaurant_id/reviews/new' => 'reviews#new', as: 'new_review'
  post '/restaurants/:restaurant_id/reviews' => 'reviews#create', as: 'post_review'
  # analytics page
  get '/analytics' => 'application#analytics', as: 'analytics'
  post '/preview' => 'reviews#homepage_poster', as: 'post_from_homepage'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    if !find_user
      redirect_to root_path
    elsif !find_restaurant
      @review = Review.new
      render :new
    elsif !@user.owns_restaurant_review(@restaurant).empty?
      redirect_to @restaurant
    else
      @review = Review.new
    end
  end

  def dummy_new
    if find_user
      @restaurant = Restaurant.new(name: session[:dummy_restaurant]["name"], address: session[:dummy_restaurant]["address"], foursquare_id: session[:dummy_restaurant]["foursquare_id"])
      # above fills in info for dummy review page
      @review = Review.new
      render :new
    else
      redirect_to login_path
    end
  end

  def create
    find_user
    if params[:restaurant]
      @restaurant = Restaurant.find_by(foursquare_id: params[:restaurant][:foursquare_id])
      @restaurant ||= Restaurant.new(foursquare_id: params[:restaurant][:foursquare_id])
      @restaurant.set_attributes
    elsif !params[:review][:restaurant_id].empty?
      @restaurant = Restaurant.find(params[:review][:restaurant_id])
    else
      @restaurant = Restaurant.find_by(foursquare_id: params[:review][:foursquare_id])
      @restaurant ||= Restaurant.create(name: session[:dummy_restaurant]["name"], address: session[:dummy_restaurant]["address"], foursquare_id: session[:dummy_restaurant]["foursquare_id"])
    end
    @review = Review.new(review_params)
    @review.user = @user
    @restaurant.set_attributes
    @restaurant.save
    @review.restaurant_id ||= @restaurant.id
    @review.calculate_review_avg
    if @review.save
      session[:dummy_restaurant] = nil
      redirect_to review_path(@review)
    else
      flash[:notice] = "You have already submitted a review for this restaurant."
      redirect_to new_review_path(@restaurant)
    end
  end

  def show
    find_review
    find_user
    @owned = @user.owns_review?(@review)
  end

  def edit
     @review = @review ? @review : find_review
     find_user
     if @user.owns_review?(@review)
       render :edit
     else
      redirect_to user_path(@user) #flash notice if user doesnt own review
    end
  end

  def update
    find_review
    @review.update(review_params)
    @review.calculate_review_avg
    redirect_to review_path(@review)
  end

  def homepage_poster
    find_user
    @review = Review.new(title: params[:review][:title], content: params[:review][:content], user_id: @user.id)
    @search = Search.create(search: params[:review][:search], location: params[:review][:location])
    @search.set_query_url
    # not sure if we can DRY up this conditional handling a 400 request
    query = RestClient.get(@search.api_url){ | response, &block |
      if response.code == 200
        response.return!
      else
        false
      end
    }
    if query
      @restaurants = JSON.parse(query)["response"]["venues"]
      @restaurants = @search.map_restaurants(@restaurants)
    else
      flash[:notice] = "No search results: make sure your location includes a state or zip code."
    end
    render :preview
  end

  def destroy
    find_review
    find_user
    @restaurant = @review.restaurant
    @review.destroy
    redirect_to user_path (@user)
  end
  private

  def review_params
    params.require(:review).permit(:title, :content, :food_rating, :environment_rating, :service_rating, :user_id, :restaurant_id, :search, :location)
  end

  def find_review
    @review = Review.find(params[:id])
  end

  # find_user
  # place in application controller? or private method in reviews

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/views/reviews/_restaurants.html.erb
  <div class="full_width_wrapper">
    <h5 class="directions">Tag your restaurant:</h5>
  </div>
  <div class="full_width_wrapper">
    <div id="results_inner_container">
      <% @restaurants.each do |restaurant| %>
    <div class="preview_result_card">
      <div class="result_card_background">
      <% if restaurant.is_a?(Restaurant) %>
      <%= radio_button("restaurant", "foursquare_id", restaurant.foursquare_id, class: 'hidden_radio', required: true) %>
      <label class="result_name" for="restaurant_foursquare_id_<%= restaurant.foursquare_id %>"><%= restaurant.name %></h4>
      <p>
        <% restaurant.address.split("~").each do |address_line| %>
        <%= address_line %><br />
        <% end %>
      </p>

      <% else %>
      <%= radio_button("restaurant", "foursquare_id", restaurant["id"], class: 'hidden_radio', required: true) %>
      <label class="result_name" for="restaurant_foursquare_id_<%= restaurant["id"] %>"><%= restaurant["name"] %></h4>
      <p>
        <% restaurant["location"]["formattedAddress"].each do |address_line| %>
        <%= address_line %><br />
        <% end %>
      </p>
      <% end %>
    </div>

    </div>
    <% end %>
  </div>
</div>

app/views/reviews/edit.html.erb
<div class="reviews_wrapper">
<div class="full_width_wrapper">
<h1 class="directive" id="new_review_directive">Editing a review for <%= link_to @review.restaurant.name, restaurant_path(@review.restaurant)%>
</h1></div>
<h5 class="directions" id="restaurant_address">
 <%= @review.restaurant.spaced_address %>
</h4>
<%= form_for @review do |f| %>
<div class="full_width_wrapper">
    <%= f.text_field :title, required: true, placeholder: "Title", autocomplete: "off" %>
</div>
<div class="full_width_wrapper">
    <%= f.text_area :content, required: true, placeholder: "Enter your review here" %>
  </div>
  <div class="full_width_wrapper">
    <h4 class="directions">From 1-5...</h4>
  </div>
<div class="full_width_wrapper">
  <div class="rating_labels_group">
    <%= f.label :food_rating, "How was the food?", class: "rating_label" %>
    <%= f.label :service_rating, "How was the service?", class: "rating_label" %>
    <%= f.label :environment_rating, "How were the vibes?", class: "rating_label" %>
  </div>
</div>
<div class="full_width_wrapper">
  <div class="ratings_group">
    <%= f.number_field :food_rating, in: 1..5, required: true, class: "rating_scale" %>
    <%= f.number_field :service_rating, in: 1..5, required: true, class: "rating_scale" %>
    <%= f.number_field :environment_rating, in: 1..5, required: true, class: "rating_scale" %>
  </div>
</div>
<div class="full_width_wrapper">
    <%= f.hidden_field :user_id, value: @user.id%>
    <%= f.hidden_field :restaurant_id, value: @review.restaurant.id %>
    <%= f.hidden_field :foursquare_id, value: @review.restaurant.foursquare_id %>
    <%= f.submit "Update Review", class: 'nav_elements submittable' %>
<% end %>
<%= form_tag review_path, method: :delete do %>
        <%= button_tag "Delete Review", class: 'nav_elements submittable' %>
<% end %>
</div>

app/views/reviews/new.html.erb
<div class="reviews_wrapper">
<div class="full_width_wrapper">
<h1 class="directive" id="new_review_directive">Writing a new review
  <% if @restaurant.id %>
  for <%= link_to @restaurant.name, restaurant_path(@restaurant)%>
  <% else %>
  for <%= @restaurant.name %>
  <% end %>
</h1></div>
<h5 class="directions" id="restaurant_address">
 <%= @restaurant.spaced_address %>
</h4>
<%= form_for @review do |f| %>
<div class="full_width_wrapper">
    <%= f.text_field :title, required: true, placeholder: "Title", autocomplete: "off" %>
</div>
<div class="full_width_wrapper">
    <%= f.text_area :content, required: true, placeholder: "Enter your review here" %>
  </div>
  <div class="full_width_wrapper">
    <h4 class="directions">From 1-5...</h4>
  </div>
<div class="full_width_wrapper">
  <div class="rating_labels_group">
    <%= f.label :food_rating, "How was the food?", class: "rating_label" %>
    <%= f.label :service_rating, "How was the service?", class: "rating_label" %>
    <%= f.label :environment_rating, "How were the vibes?", class: "rating_label" %>
  </div>
</div>
<div class="full_width_wrapper">
  <div class="ratings_group">
    <%= f.number_field :food_rating, in: 1..5, required: true, class: "rating_scale" %>
    <%= f.number_field :service_rating, in: 1..5, required: true, class: "rating_scale" %>
    <%= f.number_field :environment_rating, in: 1..5, required: true, class: "rating_scale" %>
  </div>
</div>

    <%= f.hidden_field :user_id, value: @user.id%>
    <%= f.hidden_field :restaurant_id, value: @restaurant.id %>
    <%= f.hidden_field :foursquare_id, value: @restaurant.foursquare_id %>
    <div class="full_width_wrapper new_review_page_button">
      <%= f.submit "Post Review", class: 'nav_elements', id: 'submit_post' %>
    </div>
<% end %>
</div>

app/views/reviews/preview.html.erb
<!-- this is the preview partial -->
<div class="preview_wrapper">
<%= form_for @review do |f| %>
  <div class="full_width_wrapper">
    <%= f.text_field :title, id: 'review_title', autocomplete: "off", required: true %>
  </div>
  <div class="full_width_wrapper">
    <h4 id="byline">By <%= link_to @user.name, @user, rel: "author" %></h4>
  </div>
  <div class="full_width_wrapper">
    <%= f.text_area :content, id: 'review_content', autofocus: true, required: true %>
  </div>
  <div class="full_width_wrapper">
    <h5 class="directions">On a scale of 1-5...</h4>
  </div>
  <div class="rating_labels_group">
  <%= f.label :food_rating, 'How was the food?', class: "rating_label" %>
  <%= f.label :service_rating, 'How was the service?', class: "rating_label" %>
  <%= f.label :environment_rating, 'How were the vibes?', class: "rating_label" %>
  </div>
  <div class="ratings_group">
  <%= f.number_field :food_rating, in: 1..5, class: "rating_scale", required: true %>
  <%= f.number_field :service_rating, in: 1..5, class: "rating_scale", required: true %>
  <%= f.number_field :environment_rating, in: 1..5, class: "rating_scale", required: true %>
  </div>
  <%= render "restaurants" %>
  <div class="full_width_wrapper">
  </div>
  <div id="submit_post">
    <%= f.submit 'Publish Review', class: "nav_elements submittable", id: "post_button" %>
  </div>
<% end %>
</div>

app/views/reviews/show.html.erb
<div class="reviews_wrapper">
    <h1 class="directive review-title" id="review_title"><%= @review.title %>
    </h1>
    <div class="full_width_wrapper">
      <h4 id="byline"><%= link_to @review.user.name, user_path(@review.user)%> // <%= link_to @review.restaurant.name, @review.restaurant %>
    </div>
    </h4>
    <hr class="divider" />
    <div class="full_width_wrapper">
    <section class="review_text">
      <%= simple_format(@review.content.gsub(/\r\n/, '<br/>')) %>
    </section>
  </div>
    <div class="full_width_wrapper">
    <section class="show_ratings">
    <div class="rating_labels_group">
      <p class="rating_label">FOOD</p>
      <p class="rating_label">SERVICE</p>
      <p class="rating_label">ENVIRONMENT</p>
    </div>
    <div class="ratings_group">
      <p class="rating_scale">
        <% @review.food_rating.times do |n| %><i class="fa fa-star"></i><% end %><% (5 - @review.food_rating).times do |n| %><i class="fa fa-star-o"></i><% end %>
      </p>
    <p class="rating_scale">
      <% @review.service_rating.times do |n| %><i class="fa fa-star"></i><% end %><% (5 - @review.service_rating).times do |n| %><i class="fa fa-star-o"></i><% end %>
    </p>
    <p class="rating_scale">    <% @review.environment_rating.times do |n| %><i class="fa fa-star"></i><% end %><% (5 - @review.environment_rating).times do |n| %><i class="fa fa-star-o"></i><% end %></p>
    </div>

    </section>
    </div>

  <div class="full_width_wrapper centerer">
    <% if @owned %>
        <%= form_tag edit_review_path, method: 'get', class: 'review_show_buttons' do %>
          <%= submit_tag "Edit this Review", class: 'nav_elements submittable' %>
        <% end %>
        <%= form_tag review_path, method: 'delete', class: 'review_show_buttons' do %>
          <%= submit_tag "Delete this Review", class: 'nav_elements submittable' %>
        <% end %>
    <% end %>
  </div>

</div>