config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'
  resources :users, only: [:show, :create, :edit, :update, :delete, :destroy]
  get '/reviews/new' => 'reviews#dummy_new', as: 'dummy_review'
  resources :reviews, except: [:index, :new]
  resources :upvotes, only: [:create, :destroy]
  resources :restaurants, only: [:show, :create]
  resources :searches, only: [:create, :update]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  post '/new_restaurant' => 'restaurants#dummy_create'
  get '/search/:query' => 'searches#show', as: 'search_result'
# conflict start
  get '/restaurants/:restaurant_id/reviews/new' => 'reviews#new', as: 'new_review'
  post '/restaurants/:restaurant_id/reviews' => 'reviews#create', as: 'post_review'
  # analytics page
  get '/analytics' => 'application#analytics', as: 'analytics'
  post '/preview' => 'reviews#homepage_poster', as: 'post_from_homepage'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "#{@restaurant.name} - " if @restaurant %>Palatable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="full_width_wrapper">
    <div id="nav">
      <div id="top-logo">
        <%= link_to "palatable", root_path, class: 'logo' %>
      </div>

      <%= form_for Search.new do |f| %>
        <%= f.text_field :search, placeholder: 'Search', id: 'search_field' %>
        <%= f.text_field :location, placeholder: 'ZIP or Address', required: true, id: 'location_field' %>
        <div class="submit_wrapper">
          <i class="fa fa-search fa-lg search_icon"></i>
          <%= f.submit 'Search', id: 'search_button' %>
        </div>
      <% end %>

      <div class="session_controls">
        <%= button_to "Login", login_path, class: 'nav_elements' if !logged_in? %>
        <%= link_to "Profile", @user, class: 'nav_elements' if logged_in? %>
        <%= button_to "Logout", logout_path, method: :post, class: 'nav_elements' if logged_in? %>
      </div>
    </div>
  </div>
    <%= yield %>

    <footer>
      <p id="footer_logo">
        <%= link_to "p.", root_path %>
      </p>
      <div class="full_width_wrapper"></div>

      <div class="full_width_wrapper">
      <div class="footer_text"><%= link_to "View analytics", analytics_path %></div>
      </div>

      <div class="full_width_wrapper">
      <div class="footer_text">Made with keystrokes and consternation at the <%= link_to "Flatiron School", "http://flatironschool.com" %>.</div>
      </div>
      <div class="full_width_wrapper">
      <div class="footer_text">Made + maintained: <%= link_to "@FrankieMFerreira", "https://github.com/FrankieMFerreira" %>, <%= link_to "@clintonn", "https://github.com/clintonn" %>, <%= link_to "@entcheva", "https://github.com/entcheva" %>, <%= link_to "@kighway", "https://github.com/kighway" %>.</div>
      </div>

    </footer>
  </body>
</html>